spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org:
      hibernate:
        type: trace

backpacker:
  jwt:
    secret: secret